---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: false

platforms:
- name: debian7-chef3029
  driver_config:
    box: debian-7.0.0-chef_11.4.0-chef3029-amd64
    box_url: https://onddo-vm.s3.amazonaws.com/vagrant/debian-7.0.0-chef_11.4.0-chef3029-amd64.box

suites:
- name: default
  run_list: ["recipe[chef3029]"]
  attributes: {}
